### ISSUE TITLE
有视频教程码，文字版有点看不懂，谢谢作者了！

### ISSUE THREAD

**Issue by beifengjingse** [AmbitiousJun/video-downloader-go#11]
有视频教程码，文字版有点看不懂，谢谢作者了！

**Comment by AmbitiousJun** [comment]
教程挺久没更新了，现在重新写了一版：https://github.com/AmbitiousJun/video-downloader-go?tab=readme-ov-file#%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B

按照示例跑一遍程序大概就会用了，还是不行的话可以把具体的下载需求说一下我看看

**Comment by lirangfeng** [comment]
> 教程挺久没更新了，现在重新写了一版：https://github.com/AmbitiousJun/video-downloader-go?tab=readme-ov-file#%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B
> 
> 按照示例跑一遍程序大概就会用了，还是不行的话可以把具体的下载需求说一下我看看

谢谢

**Comment by lirangfeng** [comment]
> 教程挺久没更新了，现在重新写了一版：https://github.com/AmbitiousJun/video-downloader-go?tab=readme-ov-file#%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B
> 
> 按照示例跑一遍程序大概就会用了，还是不行的话可以把具体的下载需求说一下我看看

```
===================[0m
○ [38;2;090;156;248m正在解析 m3u8 信息...[0m
○ [38;2;228;116;112m下载失败：无法获取文件总大小: 无法获取资源的 Content-Leng...[0m
○ [38;2;090;156;248m监听到下载任务，文件名：/xiazai/Video\SHErlock.S00E31.2024.108...[0m
○ [38;2;090;156;248m正在解析 m3u8 信息...[0m
○ [38;2;228;116;112m下载失败：无法获取文件总大小: 无法获取资源的 Content-Leng...[0m
[38;2;160;186;250mLog      ↑ =============================================================================================================[0m
```

老师提示这个

**Comment by lirangfeng** [comment]
# 解析器配置
#
# 注：在 windows 平台下使用 youtube-dl 解析器时，从 chrome, edge 等浏览器获取 cookie 有可能会失败，换成 firefox 即可
decoder:
  use: none # 使用哪种解析方式，可选值：none, youtube-dl, cat-catch:tx
  max-retry: 5 # 最大的尝试解析次数
  youtube-dl: # youtube-dl 解析器相关配置
    cookies-from: chrome # 从哪个浏览器获取 cookie，推荐 firefox，该参数会直接传递给 youtube-dl，传入 none 则忽略
    format-codes: # 下载视频的编码，可传多个，按照顺序进行解析，两种格式：'视频编码+音频编码' 或者 '视频编码'，只会下载首次解析成功的格式，可以不传此参数，在程序执行时手动选择
    remember-format: -1 # 是否记住视频格式，程序自动根据 host 进行区分，每次启动程序时缓存都会重置，可选值：-1, 1
  cat-catch: # 猫抓解析器
    headless: 1 # 是否开启无头模式, 可选值: -1, 1
    sites: # 针对不同的网站分别实现猫抓解析器
      tx:
        cookie-json-path: /Users/xuexi/video-downloader-windows-amd64-1.8.2/cookie-files/tx.json # Cookie 文件绝对路径
        video-format: uhd # 视频格式, 可选值: sd, hd, shd, fhd, uhd, hdr10

# 下载器配置
downloader:
  use: multi-thread # 要使用哪个下载器，可选值：simple, multi-thread
  task-thread-count: 2 # 处理下载任务的线程个数
  dl-thread-count: 12 # 多线程下载的线程个数
  download-dir: /xiazai/Video # 视频文件下载位置
  # download-dir: C:\xiazai\Video # 视频文件下载位置
  ts-dir-suffix: temp_ts_files # 暂存 ts 文件的目录后缀
  rate-limit: 10mbps # 下载限速，两种单位可选：mbps, kbps，-1 则不限速

# ts 转换器配置
#
# 对于不同的 m3u8, 有的转换器合并后的视频文件会有跳帧问题，可以尝试更换转换器
transfer:
  use: ffmpeg_str_v2 # 要选用哪个转码器，可选值：ffmpeg_str, ffmpeg_txt, ffmpeg_str_v2
  ts-filename-regex: _(\d+)\. # 正则表达式，用于匹配出 ts 文件的序号

# 针对不同的域名进行定制化配置
# 
# 针对 decoder 进行定制化配置
# 可配置的属性：use, resource-type, youtube-dl.cookies-from, youtube-dl.format-codes, youtube-dl.remember-format
#
# 针对 transfer 进行定制化配置
# 可配置的属性：use
customs:
  - decoder: 
      use: youtube-dl
      youtube-dl:
        cookies-from: chrome
        format-codes:
        remember-format: 1
    hosts: # 对哪些域名生效，必须配置完整，有端口也要加上
      - www.mgtv.com
      - www.youtube.com
      - www.bilibili.com
  - decoder:
      use: none
    hosts:
      - apd-vlive.apdcdn.tc.qq.com
      - pcvideoaliyun.titan.mgtv.com
      - pcvideotx.titan.mgtv.com

**Comment by lirangfeng** [comment]
```
# 解析器配置
#
# 注：在 windows 平台下使用 youtube-dl 解析器时，从 chrome, edge 等浏览器获取 cookie 有可能会失败，换成 firefox 即可
decoder:
  use: none # 使用哪种解析方式，可选值：none, youtube-dl, cat-catch:tx
  max-retry: 5 # 最大的尝试解析次数
  youtube-dl: # youtube-dl 解析器相关配置
    cookies-from: chrome # 从哪个浏览器获取 cookie，推荐 firefox，该参数会直接传递给 youtube-dl，传入 none 则忽略
    format-codes: # 下载视频的编码，可传多个，按照顺序进行解析，两种格式：'视频编码+音频编码' 或者 '视频编码'，只会下载首次解析成功的格式，可以不传此参数，在程序执行时手动选择
    remember-format: -1 # 是否记住视频格式，程序自动根据 host 进行区分，每次启动程序时缓存都会重置，可选值：-1, 1
  cat-catch: # 猫抓解析器
    headless: 1 # 是否开启无头模式, 可选值: -1, 1
    sites: # 针对不同的网站分别实现猫抓解析器
      tx:
        cookie-json-path: /Users/xuexi/video-downloader-windows-amd64-1.8.2/cookie-files/tx.json # Cookie 文件绝对路径
        video-format: uhd # 视频格式, 可选值: sd, hd, shd, fhd, uhd, hdr10

# 下载器配置
downloader:
  use: multi-thread # 要使用哪个下载器，可选值：simple, multi-thread
  task-thread-count: 2 # 处理下载任务的线程个数
  dl-thread-count: 12 # 多线程下载的线程个数
  download-dir: /xiazai/Video # 视频文件下载位置
  # download-dir: C:\xiazai\Video # 视频文件下载位置
  ts-dir-suffix: temp_ts_files # 暂存 ts 文件的目录后缀
  rate-limit: 10mbps # 下载限速，两种单位可选：mbps, kbps，-1 则不限速

# ts 转换器配置
#
# 对于不同的 m3u8, 有的转换器合并后的视频文件会有跳帧问题，可以尝试更换转换器
transfer:
  use: ffmpeg_str_v2 # 要选用哪个转码器，可选值：ffmpeg_str, ffmpeg_txt, ffmpeg_str_v2
  ts-filename-regex: _(\d+)\. # 正则表达式，用于匹配出 ts 文件的序号

# 针对不同的域名进行定制化配置
# 
# 针对 decoder 进行定制化配置
# 可配置的属性：use, resource-type, youtube-dl.cookies-from, youtube-dl.format-codes, youtube-dl.remember-format
#
# 针对 transfer 进行定制化配置
# 可配置的属性：use
customs:
  - decoder: 
      use: youtube-dl
      youtube-dl:
        cookies-from: chrome
        format-codes:
        remember-format: 1
    hosts: # 对哪些域名生效，必须配置完整，有端口也要加上
      - www.mgtv.com
      - www.youtube.com
      - www.bilibili.com
  - decoder:
      use: none
    hosts:
      - apd-vlive.apdcdn.tc.qq.com
      - pcvideoaliyun.titan.mgtv.com
      - pcvideotx.titan.mgtv.com
   
```

**Comment by AmbitiousJun** [comment]
> > 教程挺久没更新了，现在重新写了一版：https://github.com/AmbitiousJun/video-downloader-go?tab=readme-ov-file#%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B
> > 按照示例跑一遍程序大概就会用了，还是不行的话可以把具体的下载需求说一下我看看
> 
> ```
> ===================�[0m
> ○ �[38;2;090;156;248m正在解析 m3u8 信息...�[0m
> ○ �[38;2;228;116;112m下载失败：无法获取文件总大小: 无法获取资源的 Content-Leng...�[0m
> ○ �[38;2;090;156;248m监听到下载任务，文件名：/xiazai/Video\SHErlock.S00E31.2024.108...�[0m
> ○ �[38;2;090;156;248m正在解析 m3u8 信息...�[0m
> ○ �[38;2;228;116;112m下载失败：无法获取文件总大小: 无法获取资源的 Content-Leng...�[0m
> �[38;2;160;186;250mLog      ↑ =============================================================================================================�[0m
> ```
> 
> 老师提示这个

你是 windows 系统吗，看你提供的配置，基本都没问题，就是下载路径用的还是 unix 路径：

```
  download-dir: /xiazai/Video # 视频文件下载位置
  # download-dir: C:\xiazai\Video # 视频文件下载位置
```

在 yaml 配置中，开头加个 '#' 符号之后会被视为无效配置，如果你是 windows 系统的话，应该改成这样：

```
  # download-dir: /xiazai/Video # 视频文件下载位置
  download-dir: C:\xiazai\Video # 视频文件下载位置
```

**Comment by AmbitiousJun** [comment]
> > 教程挺久没更新了，现在重新写了一版：https://github.com/AmbitiousJun/video-downloader-go?tab=readme-ov-file#%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B
> > 按照示例跑一遍程序大概就会用了，还是不行的话可以把具体的下载需求说一下我看看
> 
> ```
> ===================�[0m
> ○ �[38;2;090;156;248m正在解析 m3u8 信息...�[0m
> ○ �[38;2;228;116;112m下载失败：无法获取文件总大小: 无法获取资源的 Content-Leng...�[0m
> ○ �[38;2;090;156;248m监听到下载任务，文件名：/xiazai/Video\SHErlock.S00E31.2024.108...�[0m
> ○ �[38;2;090;156;248m正在解析 m3u8 信息...�[0m
> ○ �[38;2;228;116;112m下载失败：无法获取文件总大小: 无法获取资源的 Content-Leng...�[0m
> �[38;2;160;186;250mLog      ↑ =============================================================================================================�[0m
> ```
> 
> 老师提示这个

还有就是你的 `data.txt` 文件是怎么写的，看这个报错日志，应该除了上面的路径问题还有其他地方配错了

**Comment by lirangfeng** [comment]
> > > 教程挺久没更新了，现在重新写了一版：https://github.com/AmbitiousJun/video-downloader-go?tab=readme-ov-file#%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B
> > > 按照示例跑一遍程序大概就会用了，还是不行的话可以把具体的下载需求说一下我看看
> > 
> > 
> > ```
> > ===================�[0m
> > ○ �[38;2;090;156;248m正在解析 m3u8 信息...�[0m
> > ○ �[38;2;228;116;112m下载失败：无法获取文件总大小: 无法获取资源的 Content-Leng...�[0m
> > ○ �[38;2;090;156;248m监听到下载任务，文件名：/xiazai/Video\SHErlock.S00E31.2024.108...�[0m
> > ○ �[38;2;090;156;248m正在解析 m3u8 信息...�[0m
> > ○ �[38;2;228;116;112m下载失败：无法获取文件总大小: 无法获取资源的 Content-Leng...�[0m
> > �[38;2;160;186;250mLog      ↑ =============================================================================================================�[0m
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 老师提示这个
> 
> 你是 windows 系统吗，看你提供的配置，基本都没问题，就是下载路径用的还是 unix 路径：
> 
> ```
>   download-dir: /xiazai/Video # 视频文件下载位置
>   # download-dir: C:\xiazai\Video # 视频文件下载位置
> ```
> 
> 在 yaml 配置中，开头加个 '#' 符号之后会被视为无效配置，如果你是 windows 系统的话，应该改成这样：
> 
> ```
>   # download-dir: /xiazai/Video # 视频文件下载位置
>   download-dir: C:\xiazai\Video # 视频文件下载位置
> ```

是win10，联想笔记本y7000 2019

**Comment by lirangfeng** [comment]
SHErlock.S00E42.2024.1080p.第二季 超前彩蛋第7期：女推团欢乐合宿夜|https://www.mgtv.com/b/696104/22302282.html?fpa=se&lastp=so_result，如果想下载腾讯该咋搞呢？

**Comment by AmbitiousJun** [comment]
> > > > 教程挺久没更新了，现在重新写了一版：https://github.com/AmbitiousJun/video-downloader-go?tab=readme-ov-file#%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B
> > > > 按照示例跑一遍程序大概就会用了，还是不行的话可以把具体的下载需求说一下我看看
> > > 
> > > 
> > > ```
> > > ===================�[0m
> > > ○ �[38;2;090;156;248m正在解析 m3u8 信息...�[0m
> > > ○ �[38;2;228;116;112m下载失败：无法获取文件总大小: 无法获取资源的 Content-Leng...�[0m
> > > ○ �[38;2;090;156;248m监听到下载任务，文件名：/xiazai/Video\SHErlock.S00E31.2024.108...�[0m
> > > ○ �[38;2;090;156;248m正在解析 m3u8 信息...�[0m
> > > ○ �[38;2;228;116;112m下载失败：无法获取文件总大小: 无法获取资源的 Content-Leng...�[0m
> > > �[38;2;160;186;250mLog      ↑ =============================================================================================================�[0m
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 老师提示这个
> > 
> > 
> > 你是 windows 系统吗，看你提供的配置，基本都没问题，就是下载路径用的还是 unix 路径：
> > ```
> >   download-dir: /xiazai/Video # 视频文件下载位置
> >   # download-dir: C:\xiazai\Video # 视频文件下载位置
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 在 yaml 配置中，开头加个 '#' 符号之后会被视为无效配置，如果你是 windows 系统的话，应该改成这样：
> > ```
> >   # download-dir: /xiazai/Video # 视频文件下载位置
> >   download-dir: C:\xiazai\Video # 视频文件下载位置
> > ```
> 
> 是win10，联想笔记本y7000 2019

那就得改一下上边说的这个下载路径

**Comment by lirangfeng** [comment]
我发现这个插件https://microsoftedge.microsoft.com/addons/detail/%E7%8C%AB%E6%8A%93/oohmdefbjalncfplafanlagojlakmjci
貌似好用一点点，但觉得up作者挺厉害的，我想尝试一下而已，不行也没关系的

**Comment by AmbitiousJun** [comment]
> SHErlock.S00E42.2024.1080p.第二季 超前彩蛋第7期：女推团欢乐合宿夜|[https://www.mgtv.com/b/696104/22302282.html?fpa=se&lastp=so_result，如果想下载腾讯该咋搞呢？](https://www.mgtv.com/b/696104/22302282.html?fpa=se&lastp=so_result%EF%BC%8C%E5%A6%82%E6%9E%9C%E6%83%B3%E4%B8%8B%E8%BD%BD%E8%85%BE%E8%AE%AF%E8%AF%A5%E5%92%8B%E6%90%9E%E5%91%A2%EF%BC%9F)

`data.txt` 没问题，你可以改完下载路径后再试试看能不能下

腾讯视频的话目前比较棘手，yt-dlp 官方迟迟不修复腾讯视频的解析，现在只能使用浏览器的 [猫抓](https://github.com/xifangczy/cat-catch) 插件抓取视频的 m3u8 地址，然后使用本仓库程序进行下载，解析器选择 `none`

**Comment by lirangfeng** [comment]
sites: # 针对不同的网站分别实现猫抓解析器
      tx:
        cookie-json-path: /Users/ambitious/Desktop/学习/Go/projects/video-downloader-go/cookie-files/tx.json # Cookie 文件绝对路径
        video-format: uhd # 视频格式, 可选值: sd, hd, shd, fhd, uhd, hdr10
这里要改吗

**Comment by lirangfeng** [comment]
> sites： # 针对不同的网站分别实现猫抓解析器 tx： cookie-json-path： /Users/ambitious/Desktop/学习/Go/projects/video-downloader-go/cookie-files/tx.json # Cookie 文件绝对路径 video-format： uhd # 视频格式， 可选值： sd， hd， shd， fhd， uhd， hdr10 这里要改吗

config.yml这个文件
[banner.txt](https://github.com/user-attachments/files/18348384/banner.txt)
[data.txt](https://github.com/user-attachments/files/18348387/data.txt)

**Comment by lirangfeng** [comment]
我大概懂了，我测试一下

**Comment by AmbitiousJun** [comment]
> sites: # 针对不同的网站分别实现猫抓解析器 tx: cookie-json-path: /Users/ambitious/Desktop/学习/Go/projects/video-downloader-go/cookie-files/tx.json # Cookie 文件绝对路径 video-format: uhd # 视频格式, 可选值: sd, hd, shd, fhd, uhd, hdr10 这里要改吗

不需要，这一段配置可以直接忽略，直接使用以下配置吧：

```yaml
# 解析器配置
#
# 注：在 windows 平台下使用 youtube-dl 解析器时，从 chrome, edge 等浏览器获取 cookie 有可能会失败，换成 firefox 即可
decoder:
  use: youtube-dl # 使用哪种解析方式，可选值：none, youtube-dl, cat-catch:tx
  max-retry: 5 # 最大的尝试解析次数
  youtube-dl: # youtube-dl 解析器相关配置
    cookies-from: chrome # 从哪个浏览器获取 cookie，推荐 firefox，该参数会直接传递给 youtube-dl，传入 none 则忽略
    remember-format: -1 # 是否记住视频格式，程序自动根据 host 进行区分，每次启动程序时缓存都会重置，可选值：-1, 1
  cat-catch: # 猫抓解析器
    headless: 1 # 是否开启无头模式, 可选值: -1, 1

# 下载器配置
downloader:
  use: multi-thread # 要使用哪个下载器，可选值：simple, multi-thread
  task-thread-count: 2 # 处理下载任务的线程个数
  dl-thread-count: 12 # 多线程下载的线程个数
  download-dir: C:\xiazai\Video # 视频文件下载位置
  ts-dir-suffix: temp_ts_files # 暂存 ts 文件的目录后缀
  rate-limit: 10mbps # 下载限速，两种单位可选：mbps, kbps，-1 则不限速

# ts 转换器配置
#
# 对于不同的 m3u8, 有的转换器合并后的视频文件会有跳帧问题，可以尝试更换转换器
transfer:
  use: ffmpeg_str_v2 # 要选用哪个转码器，可选值：ffmpeg_str, ffmpeg_txt, ffmpeg_str_v2
  ts-filename-regex: _(\d+)\. # 正则表达式，用于匹配出 ts 文件的序号
```

**Comment by lirangfeng** [comment]
```
# 解析器配置
#
# 注：在 windows 平台下使用 youtube-dl 解析器时，从 chrome, edge 等浏览器获取 cookie 有可能会失败，换成 firefox 即可
decoder:
  use: none # 使用哪种解析方式，可选值：none, youtube-dl, cat-catch:tx
  max-retry: 5 # 最大的尝试解析次数
  youtube-dl: # youtube-dl 解析器相关配置
    cookies-from: chrome # 从哪个浏览器获取 cookie，推荐 firefox，该参数会直接传递给 youtube-dl，传入 none 则忽略
    format-codes: # 下载视频的编码，可传多个，按照顺序进行解析，两种格式：'视频编码+音频编码' 或者 '视频编码'，只会下载首次解析成功的格式，可以不传此参数，在程序执行时手动选择
    remember-format: -1 # 是否记住视频格式，程序自动根据 host 进行区分，每次启动程序时缓存都会重置，可选值：-1, 1
  cat-catch: # 猫抓解析器
    headless: 1 # 是否开启无头模式, 可选值: -1, 1
    sites: # 针对不同的网站分别实现猫抓解析器
      tx:
        cookie-json-path: C:\Users\xuexi\video-downloader-windows-amd64-1.8.2\config\cookie-files\tx.json # Cookie 文件绝对路径
        video-format: uhd # 视频格式, 可选值: sd, hd, shd, fhd, uhd, hdr10

# 下载器配置
downloader:
  use: multi-thread # 要使用哪个下载器，可选值：simple, multi-thread
  task-thread-count: 2 # 处理下载任务的线程个数
  dl-thread-count: 12 # 多线程下载的线程个数
  # download-dir: /xiazai/Video # 视频文件下载位置
  download-dir: C:\xiazai\Video # 视频文件下载位置
  ts-dir-suffix: temp_ts_files # 暂存 ts 文件的目录后缀
  rate-limit: 10mbps # 下载限速，两种单位可选：mbps, kbps，-1 则不限速

# ts 转换器配置
#
# 对于不同的 m3u8, 有的转换器合并后的视频文件会有跳帧问题，可以尝试更换转换器
transfer:
  use: ffmpeg_str_v2 # 要选用哪个转码器，可选值：ffmpeg_str, ffmpeg_txt, ffmpeg_str_v2
  ts-filename-regex: _(\d+)\. # 正则表达式，用于匹配出 ts 文件的序号

# 针对不同的域名进行定制化配置
# 
# 针对 decoder 进行定制化配置
# 可配置的属性：use, resource-type, youtube-dl.cookies-from, youtube-dl.format-codes, youtube-dl.remember-format
#
# 针对 transfer 进行定制化配置
# 可配置的属性：use
customs:
  - decoder: 
      use: youtube-dl
      youtube-dl:
        cookies-from: chrome
        format-codes:
        remember-format: 1
    hosts: # 对哪些域名生效，必须配置完整，有端口也要加上
      - www.mgtv.com
      - www.youtube.com
      - www.bilibili.com
  - decoder:
      use: none
    hosts:
      - apd-vlive.apdcdn.tc.qq.com
      - pcvideoaliyun.titan.mgtv.com
      - pcvideotx.titan.mgtv.com
  
```
